os:
  - linux
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/linux-test-project/lcov.git
  - cd lcov
  - sudo make install
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
  - gem install coveralls-lcov
script:
  - ls
  - lcov -c -i -d test -o ./coverage/app_base.info
  - ./flutter/bin/flutter test
  - sudo lcov -c -d test -o ./coverage/app_test.info
  - sudo lcov -a ./coverage/app_base.info -a ./coverage/app_test.info -o ./coverage/app_total.info
after_success:
  - coveralls-lcov coverage/app_total.info
cache:
  directories:
    - $HOME/.pub-cache